### ISSUE TITLE
Segfault when audio device does not exist

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#11] opened 2017-10-08 19:03 UTC
Hi,

I have received a bug report that trackballs crashes when the audio device does not exist, e.g a laptop without soundcard. https://bugs.debian.org/877647

Maybe this can be mitigated by adding a stricter check in src/sound.cc soundInit()?

**Comment by kilobyte** [comment] 2017-10-08 19:20
> I have forwarded the bug report upstream. I am unable to reproduce the bug though, the trick with /etc/asound.conf doesn't work for me.

For the intentionally-invalid asound.conf trick, the following crashes:
```
#USB
#defaults.pcm.card 3
#defaults.ctl.card 3
built-in
defaults.pcm.card 1
defaults.ctl.card 1
```
(obviously "built-in" is a syntax error, I noticed this accidentally while trying to reproduce the crash on my big box)

> Are you sure that you have pasted the complete backtrace? I don't see anything related to trackballs.

Hmm right, that's weird.

**Comment by kilobyte** [comment] 2017-10-08 19:25
Looking more, it appears that indeed **some** other SDL2 programs crash as well — even the majority, although not all.  I don't know SDL2's startup but apparently it happens before even your code gets to run.  Thus, it looks like the bug is 100% on SDL's side.

I got fooled by testing first (and only) on a program that somehow avoids the crash.

As such, I'll investigate and report it there, it can be closed for *trackballs*.  Sorry for noise.

**Comment by mstoeckl** [comment] 2017-10-14 18:42
Closing as requested. (On a mostly-default Arch Linux, I can reproduce the crash by killing `pulseaudio` and introducing the specified invalid `asound.conf`. Then running `trackballs` yields the error message 

    ALSA lib conf.c:1876:(snd_config_load1) _toplevel_:7:0:Unexpected end of file
    ALSA lib conf.c:3636:(config_file_open) /etc/asound.conf may be old or corrupted: consider to remove or fix it
    ALSA lib conf.c:3558:(snd_config_hooks_call) function snd_config_hook_load returned error: Argument invalide
    ALSA lib conf.c:4012:(snd_config_update_r) hooks failed, removing configuration

along with a segfault which gives the same backtrace as https://bugs.debian.org/877647. Running without sound using `trackballs -m` avoids the problem.)

**Closed as completed by mstoeckl** 2017-10-14 18:42 UTC
