### ISSUE TITLE
Wrong default location for scalable images

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#15] opened 2018-03-15 13:36 UTC
Hi!

First of all thanks for the new release! I noticed that the default location for scalable images is

${TRACKBALLS_ICON}/icons/hicolor/scalable/apps/

However $TRACKBALLS_ICON is defined as /usr/share/icons/hicolor by default. While this works fine for the normal images, the scalable icon will be installed into /usr/share/icons/hicolor/icons/hicolor/scalable/apps which is the wrong directory. I suggest to change the above line to

${TRACKBALLS_ICON}/scalable/apps/

which is the correct default location for scalable images.

**Comment by mstoeckl** [comment] 2018-04-02 21:31
This should be resolved as of  451a4b3c4e4b7f33c6. 

This also corrects an issue where the documentation was installed one
directory level too high (i.e., into `/usr/share/doc/` instead of
 `/usr/share/doc/trackballs`).

**Comment by mstoeckl** [comment] 2018-05-22 13:02
Closing as the issue is fixed in v1.3.1.

**Closed as completed by mstoeckl** 2018-05-22 13:02 UTC
