### ISSUE TITLE
Installation of the highScores file into the user's home directory

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#5] opened 2017-07-22 21:36 UTC
Hi,

I am currently in the process of packaging your fork of trackballs for Debian. 

I would like to install the highScores file into the user's home directory. The original version provided a flag, --with-highscores=~ to achieve that. But looking at CMakelLsts.txt I don't see such an option for the new version. I want to avoid that the highScores file is installed into the non-writable SHARE_DIR. How can I do that?

**Comment by mstoeckl** [comment] 2017-07-23 13:21
The issue is probably resolved through a06efd3e35b6ab67c8340c344402705b0e309914 and 662df2b28ee7458bb3a4d06212fa14c73b72619. The behavior isn't quite the same as before, as `--with-highscores=~/tmp/highScores` becomes `TRACKBALLS_HIGHSCORES_DIR=~/tmp` .

Note that all of the trackballs CMake options now match the usual standard ending of _DIR.

If you want, I can make a new release including everything up to this change. I'd originally planned on doing a new release in a month or so (once I finally make a good help system and finish writing a level set).

**Comment by apoleon** [comment] 2017-07-23 13:35
Thank you. A new release would be much appreciated. There are two other issues. I will create separate bug reports for them. It would be nice if they also could be fixed for the next release but it is not urgent because I can work around them.

**Comment by mstoeckl** [comment] 2017-07-24 22:11
A new release is out, now that I've resolved those two issues with reasonable certainty.

**Comment by mstoeckl** [comment] 2017-07-29 17:47
Closing, no further issues on this topic mentioned.

**Closed as completed by mstoeckl** 2017-07-29 17:47 UTC
